# Generated by Django 3.2.7 on 2021-09-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nusnet_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
